
rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'com.cashfree.pg:api:2.4.0'
}
android {
  packagingOptions {
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/LICENSE'
  }
}
